package de.greenrobot.dao;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER_BEAN".
 */
@Entity
public class UserBean implements Serializable {

    @Id(autoincrement = true)
    private Long id;
    private String username;
    private String password;

    @Generated
    public UserBean() {
    }

    public UserBean(Long id) {
        this.id = id;
    }

    @Generated
    public UserBean(Long id, String username, String password) {
        this.id = id;
        this.username = username;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
